Repository ethereum/solc-js, pull requests merged in 2018-02, with the labels that each got.

#179 Only build on stable node version (4, 6, 8) on travis
  .travis.yml
  package.json
Labels: in progress, nextrelease

#177 Run code coverage report on coveralls
  .istanbul.yml
  .travis.yml
  README.md
  package.json
Labels: in progress, nextrelease

#178 Properly test fallback functions in abi translator
  test/abi.js
Labels: in progress, nextrelease

#176 Update translate.js
  translate.js
Labels: in progress, nextrelease

#181 Add solcjs output to .gitignore
  .gitignore
  test/package.js
Labels: in progress

#167 Use stringToUTF8 instead of deprecated writeStringToMemory
  wrapper.js
Labels: in progress

#168 Fix gas estimation translation
  translate.js
Labels: in progress, nextrelease

#182 Add comprehensive tests for the file import callback
  test/package.js
Labels: in progress, nextrelease

#185 Add more assertions to tests
  test/package.js
Labels: in progress

#186 Add helper to translate old style versions to semver
  README.md
  test/index.js
  test/package.js
  test/translate.js
  translate.js
  wrapper.js
Labels: in progress

#187 Ensure that linker tests require input bytecode
  test/package.js
Labels: in progress

#188 Support old compilers (without contract file names) in linkBytecode
  linker.js
Labels: in progress

#190 Support running compiler unit tests on older (read: <0.4.9) compilers
  test/package.js
  test/translate.js
  translate.js
Labels: in progress

#198 Raise error if invalid import callback is supplied
  test/package.js
  wrapper.js
Labels: nextrelease

#191 Legacy assembly formatter
  test/fixtureAsmJson.json
  test/fixtureAsmJson.output
  test/fixtureAsmJson.sol
  test/translate.js
  translate.js
Labels: in progress, nextrelease
